---
- name: Install mako
  community.general.xbps:
    name: mako
    state: present
  become: true
  tags: [mako]

- name: Create mako config directory
  ansible.builtin.file:
    path: "{{ user_home }}/.config/mako"
    state: directory
    mode: "0755"
  tags: [mako]

- name: Deploy mako config
  ansible.builtin.copy:
    src: mako/config
    dest: "{{ user_home }}/.config/mako/config"
    mode: "0644"
  tags: [mako]
