---
- name: Install pipewire
  community.general.xbps:
    name:
      - pipewire
      - wireplumber
      - alsa-pipewire
      - libspa-bluetooth
    state: present
  become: yes
  tags: [pipewire]

- name: Create pipewire config directories
  file:
    path: "{{ user_home }}/.config/{{ item }}"
    state: directory
  loop:
    - pipewire
    - wireplumber
  tags: [pipewire]
