---
- name: Install sway
  community.general.xbps:
    name:
      - sway
      - swaylock
      - swayidle
      - swaybg
      - wl-clipboard
      - grim
      - slurp
      - wlsunset
      - fuzzel
    state: present
  become: true
  tags: [sway]

- name: Create sway config directory
  ansible.builtin.file:
    path: "{{ user_home }}/.config/sway"
    state: directory
    mode: "0755"
  tags: [sway]

- name: Deploy sway config
  ansible.builtin.copy:
    src: sway/config
    dest: "{{ user_home }}/.config/sway/config"
    mode: "0644"
  tags: [sway]
