---
- name: Install zathura
  community.general.xbps:
    name:
      - zathura
      - zathura-pdf-mupdf
    state: present
  become: true
  tags: [zathura]

- name: Create zathura config directory
  ansible.builtin.file:
    path: "{{ user_home }}/.config/zathura"
    state: directory
    mode: "0755"
  tags: [zathura]

- name: Deploy zathura config
  ansible.builtin.copy:
    src: zathura/zathurarc
    dest: "{{ user_home }}/.config/zathura/zathurarc"
    mode: "0644"
  tags: [zathura]
