---
# lf file manager

- name: Install lf
  community.general.xbps:
    name: lf
    state: present
  tags: [lf]

- name: Create lf config directory
  file:
    path: "{{ user_home }}/.config/lf"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: [lf, config]

- name: Deploy lf config
  copy:
    src: lfrc
    dest: "{{ user_home }}/.config/lf/lfrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: no
  tags: [lf, config]
