---
# zathura PDF viewer

- name: Install zathura
  community.general.xbps:
    name:
      - zathura
      - zathura-pdf-mupdf
    state: present
  tags: [zathura]

- name: Create zathura config directory
  file:
    path: "{{ user_home }}/.config/zathura"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: [zathura, config]

- name: Deploy zathura config
  copy:
    src: zathurarc
    dest: "{{ user_home }}/.config/zathura/zathurarc"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: no
  tags: [zathura, config]
