---
# Foot terminal

- name: Install Foot terminal
  community.general.xbps:
    name: foot
    state: present
  tags: [foot, terminal]

- name: Create Foot config directory
  file:
    path: "{{ user_home }}/.config/foot"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: [foot, config]

- name: Deploy Foot config
  copy:
    src: foot.ini
    dest: "{{ user_home }}/.config/foot/foot.ini"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: no
  tags: [foot, config]
