---
- name: Install htop
  community.general.xbps:
    name: htop
    state: present

- name: Create htop config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/htop"
    state: directory
    mode: '0755'

- name: Copy htop config
  ansible.builtin.copy:
    src: htoprc
    dest: "{{ ansible_env.HOME }}/.config/htop/htoprc"
    mode: '0644'
