---
# btop system monitor

- name: Install btop
  community.general.xbps:
    name: btop
    state: present
  tags: [btop]

- name: Create btop config directory
  file:
    path: "{{ user_home }}/.config/btop"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: [btop, config]

- name: Deploy btop config
  copy:
    src: btop.conf
    dest: "{{ user_home }}/.config/btop/btop.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: no
  tags: [btop, config]
