---
# Mako notification daemon

- name: Install Mako
  community.general.xbps:
    name: mako
    state: present
  tags: [mako, notifications]

- name: Create Mako config directory
  file:
    path: "{{ user_home }}/.config/mako"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: [mako, config]

- name: Deploy Mako config
  copy:
    src: config
    dest: "{{ user_home }}/.config/mako/config"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: no
  tags: [mako, config]
